// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZKHcIWDpxZFcQNhrSRCDAVLfZffHuveM',
    appId: '1:626437912500:web:83f858706055a915dce4e1',
    messagingSenderId: '626437912500',
    projectId: 'chatapp-98340',
    authDomain: 'chatapp-98340.firebaseapp.com',
    storageBucket: 'chatapp-98340.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVmEWAORE7yPm23i4lFa5Muzq7yVyrF50',
    appId: '1:626437912500:android:c3b41e52ecebf06bdce4e1',
    messagingSenderId: '626437912500',
    projectId: 'chatapp-98340',
    storageBucket: 'chatapp-98340.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR2BACjj1du_PC3hFQS3ItCckBc9DxeIs',
    appId: '1:626437912500:ios:3f6a846b53bff224dce4e1',
    messagingSenderId: '626437912500',
    projectId: 'chatapp-98340',
    storageBucket: 'chatapp-98340.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR2BACjj1du_PC3hFQS3ItCckBc9DxeIs',
    appId: '1:626437912500:ios:5621d64185421e7adce4e1',
    messagingSenderId: '626437912500',
    projectId: 'chatapp-98340',
    storageBucket: 'chatapp-98340.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
